### ISSUE TITLE
Error when trying to run the test

### ISSUE THREAD

**Issue by chihau** [testmunk/TMSampleAndroid#2]
I have this error when I am trying to run the samples testcases.

```
$ calabash-android run app-debug.apk -verbose
No test server found for this combination of app and calabash version. Recreating test server.
/Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.12/lib/calabash-android/helpers.rb:173:in `scan': invalid byte sequence in US-ASCII (ArgumentError)
    from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.12/lib/calabash-android/helpers.rb:173:in `extract_md5_fingerprint'
    from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.12/lib/calabash-android/helpers.rb:165:in `block (2 levels) in fingerprint_from_apk'
    from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.12/lib/calabash-android/helpers.rb:145:in `chdir'
    from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.12/lib/calabash-android/helpers.rb:145:in `block in fingerprint_from_apk'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
    from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.12/lib/calabash-android/helpers.rb:144:in `fingerprint_from_apk'
    from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.12/bin/calabash-android-build.rb:2:in `calabash_build'
    from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.12/lib/calabash-android/helpers.rb:100:in `build_test_server_if_needed'
    from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.12/bin/calabash-android-run.rb:16:in `calabash_run'
    from /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.12/bin/calabash-android:85:in `<top (required)>'
    from /usr/bin/calabash-android:23:in `load'
    from /usr/bin/calabash-android:23:in `<main>'
```

I am running: 
OSX 10.10.4 Yosemite
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)

**Comment by lukaszfryc** [comment]
Hi! 

Have you tried http://stackoverflow.com/questions/25807913/found-scan-invalid-byte-sequence-in-cp950-argumenterror-while-running-cal ?
